# docker-compose.yml
version: '2'

services:
  backend:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/python-docker
  duplicates_store:
    image: mongo:latest
    volumes:
      - ./DuplicatesStore/data/db:/data/db
    ports:
      - 27017:27017
networks:
  image_network:
    name: image_network
    driver: bridge