# docker-compose.yml
version: '2'

services:
  backend:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/python-docker
  scheduler:
    build: ./Scheduler
    volumes:
      - ./:/python-docker # todo: ./scheduler
  duplicates_store:
    image: mongo:latest
    volumes:
      - ./DuplicatesStore/data/db:/data/db
    ports:
      - 27017:27017
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
#      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # todo: Check DNS name resolution in local area network
      - backend_url="http://192.168.1.38:5000/"
      - image_provider_url="http://192.168.1.38:8000/"
networks:
  image_network:
    name: image_network
    driver: bridge